version: '3.8'

services:
  app-storage:
    build:
      context: .
      dockerfile: ../AppAvailabilityTracker.Services.AppStorage.Web/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      urls__GooglePlayAppCheckerServiceUrl: "http://google-play-market-app-checker:8080"
      urls__AppStoreAppCheckerServiceUrl: "http://app-store-app-checker:8080"
      EventBusConfiguration__Host: "rabbitmq"
    depends_on:
      - postgres
      - rabbitmq
      - google-play-market-checker
      - app-store-checker
    ports:
      - "8080:8080"
      - "8081:8081"

  google-play-market-checker:
    build:
      context: .
      dockerfile: ../AppAvailabilityTracker.Services.AppChecker.Web/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ServiceConfiguration__Name: "GooglePlayMarketChecker"
      EventBusConfiguration__Host: "rabbitmq"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8082:8080"
      - "8083:8081"

  app-store-checker:
    build:
      context: .
      dockerfile: ../AppAvailabilityTracker.Services.AppChecker.Web/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ServiceConfiguration__Name: "AppStoreChecker"
      EventBusConfiguration__Host: "rabbitmq"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8084:8080"
      - "8085:8081"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata_dev:
