// <auto-generated />
using System;
using AppAvailabilityTracker.Services.AppChecker.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppAvailabilityTracker.Services.AppChecker.Infrastructure.Migrations
{
    [DbContext(typeof(AvailabilityCheckContext))]
    partial class AvailabilityCheckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppAvailabilityTracker.Services.AppChecker.Infrastructure.Models.AvailabilityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_link");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<bool>("CheckResult")
                        .HasColumnType("boolean")
                        .HasColumnName("check_result");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_time");

                    b.HasKey("Id")
                        .HasName("availability_checks_pkey");

                    b.ToTable("availability_checks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
